spring:
    application:
        name: User Management API

# H2 Database Configuration
    datasource:
        url: jdbc:h2:mem:test_db
        driver-class-name: org.h2.Driver
        username: sa
        password: 

# H2 Console (for development)
    h2:
        console:
            enabled: true
            path: /h2-console

# JPA Configuration
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                format_sql: false

# Logging Configuration
logging:
  level:
    org.springdoc: WARN
    org.hibernate: WARN
    org.springframework.web: INFO
    io.dhlottery.user: INFO
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    writer-with-default-pretty-printer: true
    swagger-ui:
        path: /swagger-ui.html  # Swagger UI 접근 경로
        enabled: true
        try-it-out-enabled: true
        operations-sorter: alpha
        tags-sorter: alpha
        doc-expansion: none
    api-docs:
        path: /api-docs
        enabled: true
    show-actuator: false
    model-and-view-allowed: false

# Server Configuration
server:
    port: 8080